import About from '@/components/About';
import Banner from '@/components/Banner'
import Navbar from '@/components/Navbar'
import Head from 'next/head'

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-slate-200 h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <section id='banner' className='snap-start'>
        <Banner />
      </section>

      <section id='about' className='snap-center'>
        <About />
      </section>
    </div>
  );
}
